Agricoop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('registration.urls')),
    path('addgroup/',include('addgroup.urls')),
    path("group_details/",include("group_details.urls")),
    path("payments/",include("payments.urls")),
    path('settings/', include("settings.urls")),
    path('mympesa', include('mympesa.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=staticfiles_urlpatterns()

Api/urls.py
from django.urls.conf import include, path
from rest_framework import routers
from .views import LoginViewSet
from .views import SignUpViewSet
from .views import PaymentViewSet
from .views import BaseModelViewset
from .views import MpesaCallsViewset
from .views import MpesaCallBacksViewset
from .views import MpesaPaymentViewset
router=routers.DefaultRouter()
router.register("login/",LoginViewSet)
router.register("register/",SignUpViewSet)
router.register("dashboard/",PaymentViewSet)
router.register("basemodel/",BaseModelViewset)
router.register("mpesacalls/",MpesaCallsViewset)
router.register("mpesacallbacks/",MpesaCallBacksViewset)
router.register("mpesapayment/",MpesaPaymentViewset)
urlpatterns = [
   path("",include(router.urls))
]

addgroup/urls.py
from django.urls import path
from .views import add_group,display_group


app_name = 'addgroup'
urlpatterns = [
    path("add_group/",add_group,name="add_group"),
    path("display/", display_group, name="display_group"),
]
    

group_details/urls.py
from django.urls import path

from .views import group_details,display_beans,edit,delete

app_name = 'group_details'
urlpatterns = [

        path("group_details/<int:id>/",group_details,name="group_details"),
        path("group_details/",display_beans,name="list"),
        path("edit/<int:id>/",edit,name="edit"),
        path("delete/<int:id>/",delete,name="delete")
]

payments/urls.py
from django.urls import path
from .views import payments,payment_list,edit,delete,lipa
from django.conf import urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


app_name = 'payments'
urlpatterns = [
    path("payments/",payments,name="payments"),
    path("list/",payment_list,name="payment_list"),
    path("edit/<int:id>/",edit,name="edit"),
    path("delete/<int:id>/",delete,name="delete"),
    path("lipa",lipa,name="lipa"),
    

]

group_details/models.py
from django.db import models
import datetime
from django.db.models.deletion import CASCADE

from addgroup.models import Group_list



class Delivaries(models.Model):
    group_name=models.ForeignKey(Group_list,max_length=200,null=True,on_delete=CASCADE)
    date_of_delivery=models.DateTimeField(null=True)
    beans_variety_choice= (
        ('Bush beans','Bush beans'),
        ('Climbing beans','Climbing beans'),
        ('Ruvuninkingi','Ruvuninkingi'),
        )
    beans_variety=models.CharField(max_length=200,choices= beans_variety_choice,null=True)
    kgs_of_beans= models.PositiveSmallIntegerField(null=True)
    price_per_kg=models.PositiveSmallIntegerField(null=True)

    @property
    def total_amount(self):
        total_amount=self.kgs_of_beans* self.price_per_kg
        return total_amount    

    def __str__(self):
        return self.group_name.group_name    

group_details/forms.py
from django import forms
from django.db import models
from django.db.models.base import Model
from django.forms import fields
from .models import Delivaries

class GroupRegistrationForm(forms.ModelForm):
    class Meta:
        model= Delivaries
        fields= "__all__"

group_details/views.py
from django.shortcuts import  render, redirect

from addgroup.models import Group_list
from .forms import GroupRegistrationForm
from .models import Delivaries
from  addgroup.models import Group_list
from django.http.response import HttpResponseRedirect
from django.urls import reverse

def group_details(request,id):
    groups=Group_list.objects.get(id = id)
    if request.method=="POST":
        form = GroupRegistrationForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect("group_details:list")
        else:
            print(form.errors)
    else:
        form= GroupRegistrationForm()
    return render(request,"group_details.html",{"form":form,"groups":groups})


def display_beans(request):
    products=Delivaries.objects.all()
    return render(request,"bean_details.html",{"products":products})

def edit(request,id):
    product=Delivaries.objects.get(id=id)
    if request.method=="POST":
        form=GroupRegistrationForm(request.POST,instance=product)
        if form.is_valid():
            form.save()
            return redirect("group_details:list")
    else:
        form=GroupRegistrationForm(instance=product)
        return render(request,"edit.html",{"form":form})

def delete(request,id):
    product=Delivaries.objects.get(id=id)
    if request.method=='POST':
        product.delete()
        return HttpResponseRedirect(reverse("group_details:list"))
    context={"product":product}
    return render(request,'delete.html')

group_details/templates/Delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
</head>
<body>
    <p>Are you sure you want to delete?</p>
    <a href="{% url 'group_details:list' %}"><button>Cancel</button></a>
    <form method="POST" action="">
    {% csrf_token %}
    <input type="submit" name="confirm">
</form>
</body>
</html>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        <h1> Edit details </h1>
        {{form.as_p}}
        <input type="submit" value="Submit" id="button">
    </form>
    <table id="table">
        {% for group_details in product %}
        <tr>
          <td>{{group_details.date_of_delivery}}</td>
          <td>{{group_details.beans_variety}}</td>
          <td>{{group_details.group_name}}</td>
          <td>{{group_details.kgs_of_beans}}</td>
          <td>{{group_details.Price_per_kg}}</td>
          <td>{{group_details.total_amount}}</td>
      </tr>
      {% endfor %}
    </table>
    <style>
        #table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 20%;
            font-family: 'Nunito', sans-serif;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
        }
        #table tr:nth-child(even){
            background-color: #f2f2f2be;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            color:black;
            font-family: 'Nunito', sans-serif;
        }
    </style>
</body>
</html>

group_details/templates/bean_details.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Group List</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
  <div class="content" >
    <div class="row my-3 p-3">

          <div class="sidebar-nav">
            <img src="{% static 'imges/Farm to Plate.png' %}" alt="" style="width:90px; height: 90px; margin-left: 28px; margin-bottom: 20px; border-radius: 5%;">
            <a href="{% url 'addgroup:display_group' %}">Home</a>
            <a href="{% url 'addgroup:add_group' %}">Add group</a>
            <a href="{% url 'group_details:list' %}">Deliveries</a>
            <a href="{% url 'payments:payments' %}">Payments</a>
            <a href="{%url 'setting_page'%}">Settings</a>
            <a href="{% url 'login'%}">LogOut</a>
          </div>
     </div>
    <div>

        <table id="table">
          <center><h1>Beans</h1> </center>
          <hr>
            <tr>
                <th>Group name</th>
                <th>Bean variety</th>
                <th>Delivery  date</th>
                <th>Total kgs</th>
                <th>Price per kg</th>
                <th>Edit</th>
                <th>Delete</th>
                <!-- <th>Status</th> -->

            </tr>

            
            {% for group_details in products %}
             <td>{{group_details.group_name}}</td>
              <td>{{group_details.beans_variety}}</td>
              <td>{{group_details.date_of_delivery}}</td>
              <td id="one">{{group_details.kgs_of_beans}}</td>
              <td>{{group_details.price_per_kg}}</td>
              <td><a href="{% url 'group_details:edit' id=group_details.id %}"><img src="https://icons-for-free.com/iconfiles/png/512/svg+create+edit+edit+file+office+pencil+writing+creativ+icon-1320185158722776676.png" alt="" id="image"></a></td>
              <td><a href="{% url 'group_details:delete' id=group_details.id %}"><img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/delete-2471204-2066711.png" alt="" id="img"></a></td>
              <td class="status">{{group_details.status}}</td>
          </tr>
          </tr>
          {% endfor %}

        </form>

        </table>
    </div>
    <script>
      function toggleAddBtn() {
    var div = document.getElementById("bg-modal");
     div.style.position='absolute'
     div.style.top = 0
     div.style.margin = '8% 32%'
     div.style.boxShadow = '5px 10px 8px 10px #888888'
     div.classList.toggle('hidden')
}
    </script>
  <style type="text/css">
  body{
    background-color:#b4bfcc ;
    margin-top: 0;
    font-family: 'Nunito', sans-serif;
  }
  #image{
    width: 35px;
  }
  #img{
    width: 23px;
  }
  .sidebar-nav{
    height: 100%;
    width: 180px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #192E5B;
    overflow: hidden;
    padding-top: 20px;

  }
 
  .sidebar-nav a{
    padding:13px 13px 13px 30px;
    text-decoration: none;
    font-size: 18px;
    color: #F1F1F1;
    display: block;
    font-family: 'Nunito', sans-serif;
    font-weight: bold;
    }
  .sidebar-nav a:hover{
    color: black;
        }
  h3{
    color: black;
    font-size: 30px;
    margin-left: 200px;
    font-family: 'Nunito', sans-serif;
  }
  #table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 20%;
            margin-top: 50px;
            font-family: 'Nunito', sans-serif;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
        }
        #table tr:nth-child(even){
            background-color: #ffffff;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            color:black;
            font-family: 'Nunito', sans-serif;
        }
        @media screen and (max-width: 960px) {
  .sidebar-nav >a {
     font-size: 13px;
    margin-top: -15px;
    height: 30px;
  }
  }
@media screen and (max-width: 960px) {
  .sidebar-nav{
    height: 90%;
    width: 30%;
  }
}
@media screen and (max-width: 768px) {
  #table{
    width: 65%;
    margin-left: 35%; 
    font-size: 40%;
   }
}
@media screen and (max-width: 768px) {
  #image{
    width: 20px;
  }
}
@media screen and (max-width: 768px) {
  #img{
    width: 14px;
  }
}
  </style>
</body>
</html>

group_details/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        <h1> Edit details </h1>
        {{form.as_p}}
        <input type="submit" value="Submit" id="button">
    </form>
    <table id="table">
        {% for group_details in product %}
        <tr>
          <td>{{group_details.date_of_delivery}}</td>
          <td>{{group_details.beans_variety}}</td>
          <td>{{group_details.group_name}}</td>
          <td>{{group_details.kgs_of_beans}}</td>
          <td>{{group_details.Price_per_kg}}</td>
          <td>{{group_details.total_amount}}</td>
      </tr>
      {% endfor %}
    </table>
    <style>
        #table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 20%;
            font-family: 'Nunito', sans-serif;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
        }
        #table tr:nth-child(even){
            background-color: #f2f2f2be;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            color:black;
            font-family: 'Nunito', sans-serif;
        }
    </style>
</body>
</html>

group_details/templates/group_details.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Group Details</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
   <!-- Font Awesome -->
   <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
   <!-- Moment.js -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>
   <!-- Tempus Dominus Bootstrap 4 -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
    <style>
body{
    background-color:#b4bfcc;
    margin-top: 0;
}
.head{
    color: rgb(112, 22, 112);
    font-size: 25px;
    text-align: center;
    margin-bottom: 40px;
    padding-top: 40px;
}
.container{
    margin-left: 400px;
    width: 700px;
    padding: 2px;
    font-size: 20px;
    border-radius: 30px;
    margin-right: -250px;
}
input{
                width: 90%;
                border-radius: 10px;
                padding: 8px 2px;
                border: 1px solid black;
                font-family: 'Nunito', sans-serif;
                outline: none;
            }
            select{
              width: 90%;
                border-radius: 10px;
                padding: 8px 10px;
                border: 1px solid black;
                font-family: 'Nunito', sans-serif;
                outline: none;
                -webkit-appearance: none;
                background-color: white;
            }
  .sidebar-nav{
    height: 100%;
    width: 180px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color:#192E5B;
    overflow: hidden;
    padding-top: 20px;
  }
  .sidebar-nav a{
    padding:13px 13px 13px 30px;
    text-decoration: none;
    font-size: 18px;
    color: #F1F1F1;
    display: block;
    font-family: 'Nunito', sans-serif;
    font-weight: bold;
    }

  .sidebar-nav a:hover{
    color: black;
}
h3{
    color: black;
    font-size: 30px;
    text-align: center;
    font-family: 'Nunito', sans-serif;
  }
  .button-add{
  background-color: #192E5B;
  border: none;
  color: white;
  text-align: center;
 width: 90%;
 font-size: 20px;
  position: relative;
  cursor: pointer;
  top: 20px;
}
a{
  color: white;
  text-decoration: none;
}
a:hover{
  color:black;
}
.submit2{
  text-decoration-style:none;
  top: 30px;
  height: 50px;
  width :13%;
  padding: 3px 2px;
  border-radius: 10px;
  align-items: center;
  font-size: 1.4rem;
  margin-left: 64%;
  position: relative;
  bottom: 200px;
  background-color: #192E5B;
  color: white;
  font-family: 'Nunito', sans-serif;
}
h1{
  font-family: 'Nunito', sans-serif;
  }
  @media screen and (max-width: 960px) {
  .sidebar-nav >a {
     font-size: 13px;
    margin-top: -2px;
  }
  }
@media screen and (max-width: 960px) {
  .sidebar-nav{
    height: 90%;
    width: 30%;
  }
}
@media screen and (max-width: 768px) {
.container{
   margin-left:35%;
   width: 50%;
   }
}
@media screen and (max-width: 768px) {
.submit2{
  font-size: 90%;
  width: 30%;
  height: 30px;
}
}
    </style>
</head>
<body>
    <div class="container">
      <h1>{{groups.group_name}}</h1>
        <form method="POST" enctype="multipart/form-data">
          {%csrf_token%}
          {{form.as_p}}
  <!-- clender -->
      <input type="submit" value="Confirm delivery" class="button-add">
</div>
</div>
<div class="sidebar-nav">
  <img src="{% static 'imges/Farm to Plate.png' %}" alt="" style="width: 90px; height: 90px; margin-left: 28px; margin-bottom: 20px; border-radius: 5%;">
  <a href="{% url 'addgroup:display_group' %}">Home</a>
  <a href="{% url 'addgroup:add_group' %}">Add group</a>
  <a href="{% url 'group_details:list' %}">Deliveries</a>
  <a href="{% url 'payments:payments' %}">Payments</a>
  <a href="{%url 'setting_page'%}">Settings</a>
  <a href="{% url 'login'%}">LogOut</a>
</div>
<button class="submit2"><a href="{% url 'group_details:list' %}">View deliveries</a></button>
<!-- script -->
<script>
  $(function () {
    $("#datetimepicker1").datetimepicker();
  });
 $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>
</body>
</html>