Agricoop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('registration.urls')),
    path('addgroup/',include('addgroup.urls')),
    path("group_details/",include("group_details.urls")),
    path("payments/",include("payments.urls")),
    path('settings/', include("settings.urls")),
    path('mympesa', include('mympesa.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=staticfiles_urlpatterns()

Api/urls.py
from django.urls.conf import include, path
from rest_framework import routers
from .views import LoginViewSet
from .views import SignUpViewSet
from .views import PaymentViewSet
from .views import BaseModelViewset
from .views import MpesaCallsViewset
from .views import MpesaCallBacksViewset
from .views import MpesaPaymentViewset
router=routers.DefaultRouter()
router.register("login/",LoginViewSet)
router.register("register/",SignUpViewSet)
router.register("dashboard/",PaymentViewSet)
router.register("basemodel/",BaseModelViewset)
router.register("mpesacalls/",MpesaCallsViewset)
router.register("mpesacallbacks/",MpesaCallBacksViewset)
router.register("mpesapayment/",MpesaPaymentViewset)
urlpatterns = [
   path("",include(router.urls))
]

addgroup/urls.py
from django.urls import path
from .views import add_group,display_group


app_name = 'addgroup'
urlpatterns = [
    path("add_group/",add_group,name="add_group"),
    path("display/", display_group, name="display_group"),
]
    

group_details/urls.py
from django.urls import path

from .views import group_details,display_beans,edit,delete

app_name = 'group_details'
urlpatterns = [

        path("group_details/<int:id>/",group_details,name="group_details"),
        path("group_details/",display_beans,name="list"),
        path("edit/<int:id>/",edit,name="edit"),
        path("delete/<int:id>/",delete,name="delete")
]

payments/urls.py
from django.urls import path
from .views import payments,payment_list,edit,delete,lipa
from django.conf import urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


app_name = 'payments'
urlpatterns = [
    path("payments/",payments,name="payments"),
    path("list/",payment_list,name="payment_list"),
    path("edit/<int:id>/",edit,name="edit"),
    path("delete/<int:id>/",delete,name="delete"),
    path("lipa",lipa,name="lipa"),
    

]

addgroup/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User

class Group_list(models.Model):
    group_name_choice= (
        ('Iwacu group','Iwacu group'),
        ('Komera cooperative','Komera cooperative'),
        ('Ubwiyunge cooperative','Ubwiyunge cooperative'),
        ('Green farm cooperative','Green farm cooperative'),
        ('Uwase cooperative','Uwase cooperative'),

        )
    group_name=models.CharField(max_length=200,choices= group_name_choice,null=True)
    no_of_members=models.PositiveSmallIntegerField()
    profile = models.ImageField(default='default.jpg', upload_to='static/images', null=True)
    id=models.CharField(max_length=100, primary_key=True)
    phone_number=models.CharField(max_length=100)
    payment_status=models.CharField(max_length=240,null=True,default="Unpaid")

    def __str__(self) :
        return self.group_name
   
    

addgroup/forms.py
from django import forms
from django.forms import fields
from addgroup.models import Group_list
from.models import Group_list

class GroupRegistrationForm(forms.ModelForm):
    class Meta:
        model = Group_list
        fields='__all__' 

addgroup/views.py
from django.contrib.auth.models import Group
from django.shortcuts import render

from django import forms
from django.shortcuts import  render, redirect

from addgroup.models import Group_list
from .forms import GroupRegistrationForm
from django.contrib.auth.decorators import login_required

@login_required
def profile(request):
    return render(request, 'users/profile.html')

def add_group(request):
    if request.method=="POST":
        form=GroupRegistrationForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)

    else:
        form=GroupRegistrationForm()
    return render(request,"add_group.html",{"form":form})

def display_group(request):
    groups= Group_list.objects.all()
    return render(request,"display_group.html", {"groups":groups})

addgroup/templates/Delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">


    <title>Document</title>
</head>
<body>
    <p>Are you sure you want to delete?</p>
    <a href="{% url 'group_details:list' %}"><button>Cancel</button></a>
    <form method="POST" action="">
    {% csrf_token %}
    <input type="submit" name="confirm">
</form>
</body>
</html>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        <h1> Edit details </h1>
        {{form.as_p}}
        <input type="submit" value="Submit" id="button">
    </form>
    <table id="table">
        {% for group_details in product %}
        <tr>
          <td>{{group_details.date_of_delivery}}</td>
          <td>{{group_details.beans_variety}}</td>
          <td>{{group_details.group_name}}</td>
          <td>{{group_details.kgs_of_beans}}</td>
          <td>{{group_details.Price_per_kg}}</td>
          <td>{{group_details.total_amount}}</td>
      </tr>
      {% endfor %}
    </table>
    <style>
        #table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 20%;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
            font-family: 'Nunito', sans-serif;
        }
        #table tr:nth-child(even){
            background-color: #f2f2f2be;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            color:black;
            font-family: 'Nunito', sans-serif;
        }
    </style>
</body>
</html>

addgroup/templates/add_group.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Group List</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
  <style type="text/css">
  body{
    margin:0;
    background-color:#b4bfcc;
    }
   .reg{
    padding:180px;
    width:350px;
    height:240px;
    overflow:hidden;
    background:#fcfafb;
    border-radius:10px;
    margin-left:30%;
    margin-top: 2%;
    font-family: 'Nunito', sans-serif;
          }
.reg:hover{
    background: rgba(107, 121, 150, 0.659);
          }
.content{
  margin-top: -18%;
}
    button{
     background-color: #192E5B;
     width: 45%;
      color: black;
      font-size: 14px;
      padding: 30px;
      margin: 10px 0px;
      border: none;
      cursor: pointer;
      border-radius: 20px;
      font-family: 'Nunito', sans-serif;
     }
  .sidebar-nav{
    height: 100%;
    width: 180px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color:#192E5B;
    overflow: hidden;
    padding-top: 20px;
  }
  .sidebar-nav a{
    padding:13px 13px 13px 30px;
    text-decoration: none;
    font-size: 18px;
    color: #F1F1F1;
    display: block;
    font-family: 'Nunito', sans-serif;
    font-weight: bold;
    }
  .sidebar-nav a:hover{
    color: black;
        }
  h1{
    text-align: center;
    text-decoration-color: black;
    margin-top: 0%;
    font-family: 'Nunito', sans-serif;
  }
  h3{
    color: black;
    font-size: 20px;
    margin-left: 20%;
    text-align: center;
    margin-right:60px;
    margin-bottom: 3%;
    font-family: 'Nunito', sans-serif;  }
  h4{
    color: black;
    font-size: 18px;
    margin-left: 20px;
    position: relative;
    bottom: -40px;
    width:28% ;
    font-family: 'Nunito', sans-serif;
  }
  #group{
    background-color: white;
    padding: 8px 250px;
    text-align: right 100px;
    text-align: top;
    box-shadow: 0 0 5px black;
    margin-left: -35%;
    font-size: small;
    font-family: 'Nunito', sans-serif;
  }
  #leader{
    background-color: white;
    padding: 15px 350px;
  }
  #members{
    background-color: white;
    padding: 18px 250px;
    text-align: right 100px;
    text-align: top;
    box-shadow: 0 0 5px black;
    margin-left: -35%;
    font-size: small;
    font-family: 'Nunito', sans-serif;
  }
.button {
  background-color: #192E5B;
  border: none;
  color: white;
  padding: 15px 60px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 24px;
  margin-left: 500px;
  position: relative;
  bottom: -50px;
  border-radius: 10px;
  cursor: pointer;
}
#addbutton {
  background-color: #192E5B;
  border: none;
  color: #FFFFFF;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  position: relative;
  bottom: 302px;
  cursor: pointer;
  margin-left: 75%;
  border-radius: 50%;
  width: 2.6%;
  height: 2%;
  padding: 5px;
}
#addbutton2 {
  background-color: #192E5B;
  border: none;
  color: #FFFFFF;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  position: relative;
  bottom: 288px;
  cursor: pointer;
  margin-left: 75%;
  border-radius: 50%;
  width: 2.6%;
  height: 2%;
  padding: 5px;
}
 .mybutton {
  background-color: #192E5B;
  border: none;
  color: white;
 padding: 15px 60px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  margin-left: 150px;
  position: relative;
  bottom: -90px;
  border-radius: 10px;
  cursor: pointer;
}
 #btn {
  background-color: #192E5B;
  border: none;
  color: white;
  padding: 15px 60px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  margin-left: 550px;
  position: relative;
  bottom: -90px;
  border-radius: 10px;
  cursor: pointer;
}
/* pop up one */
.hidden{
  justify-content: center;
  align-items: center;
  position: absolute;
  top: 0;
  margin:15% 32%;
  display: none;
}
.entry{
  background-color: whitesmoke;
  padding-left: 5%;
  width: 600px;
}
.entries{
  background-color:whitesmoke;
  padding-left: 5%;
  width: 600px;
  font-family: 'Nunito', sans-serif;
}
.hidden2{
   display: flex;
  justify-content: center;
  align-items: center;
  position: absolute;
  top: 0;
  margin:8% 32%;
  display: none;
}
.modal-content2{
  width: 800px;
  height: 550px;
 background-color:whitesmoke;
}
input{
  width: 50%;
  padding: 10px;
  position: relative;
  bottom: -50px;
  margin-left: 100px;
}
 input{
  width: 50%;
  border: 2px;
  margin: 8px 0;
  outline: none;
  margin-left: 200px;
  padding-bottom: 28px;
  position: relative;
  font-size: 15px;
  font-weight: bold;
}
input[type=text1]{
  padding: 5% 51%;
  box-shadow: 0 0 5px black;
  text-align: center;
  margin-left: -35%;
  margin-right: -42%;
  width: 68%;
  font-size: 12px;
  font-weight: lighter;
}
h5{
  padding: 5px 100px;
}
h2{
  text-align: center;
  font-size: 20px;
}
form input{
  position: relative;
  bottom: 4px;
  align-items: center;
}
form{
  position: relative;
  bottom: -20px;
}
.submit1{
  text-decoration-style:none;
  top: 60px;
  padding: 5px 10px;
  border-radius: 6px;
  align-items: center;
  font-size: 1.4rem;
  margin-left: 120px;
  position: relative;
  bottom: 100px;
}.submit1 a{
  color: #F1F1F1;
  text-decoration: none;
}
.submit2{
  text-decoration-style:none;
  top: 0px;
  height: 50px;
  width :30%;
  border-radius: 6px;
  align-items: center;
  font-size: 1.4rem;
  margin-left: 200px;
  position: relative;
  bottom: 200px;
  background-color: #192E5B;
  color: white;
}

@media screen and (max-width: 960px) {
  .sidebar-nav{
  width:8%;
  font-size: 16%;
  }
.sidebar-nav >a {
  font-size: 70%;
  }
  #group{
    width: 8%;
    height: 900%;
    padding: 2px 90px;
    margin-left: 17%;
   }
   h3{
  margin-left:-40%;
  top: 50%;
  }
#members{
    padding: 7px 90px;
     margin-left: 17%;
     width: 8%;
    font-size: 50%;
  }
   #addbutton {
   right:135%;
   bottom: 72px;
   padding: 1px 6px;
   margin-left:50%;
}
   #addbutton {
   right:-160%;
   bottom: 72px;
   padding: 1px 6px;
}

 #addbutton2 {
   right:60%;
   bottom: 55px;
   padding: 1px 6px;
  }
 .submit1{
  right:60%;
  height: 30px;
  width :25%;
  font-size: 9px;
  }

  input{
  right:21%;
  height: 1px;
  width :38%;
  font-size: 9px;
}
}
</style>
</head>
<body>
  <div class="row my-3 p-3">
    <div class="sidebar-nav">
      <img src="{% static 'imges/Farm to Plate.png' %}" alt="" style="width: 90px; height: 90px; margin-left: 28px; margin-bottom: 20px; border-radius: 5%;">
      <a href="{% url 'addgroup:display_group' %}">Home</a>
      <a href="{% url 'addgroup:add_group' %}">Add group</a>
      <a href="{%url 'group_details:list' %}">Deliveries</a>
      <a href="{% url 'payments:payments' %}">Payments</a>
      <a href="{%url 'setting_page'%}">Settings</a>
      <a href="{% url 'login'%}">LogOut</a>
    </div>
</div>
<div class="reg">
<div class="content" >
  <h3>Add group</h3>
  <div class="input-field">
    <input type="text1" id="name" value="Name of the group">
    <h4 id="group">Group leader details</h4>
     <h4 id="members">Group members</h4>
     <button class="submit1"><a href="{% url 'addgroup:display_group' %}">View groups</a></button>
  </div>
   </div>
   </div>
   <button onclick="toggleAddBtn()" id="addbutton">+</button>
   <button onclick="toggleAddBtn2()" id="addbutton2">+</button>

  <div id="bg-modal"  class="hidden">
    <div class="entry">
      <form method="POST">
     <h2>Group leader details</h2>
     <div class="wrapper">
        <div class="form">
     <form method="POST" enctype="multipart/form-data">
         {%csrf_token%}
         {{form.as_p}}
         {{Name}}
         <button class="submit2">Submit</button>
     </form>
     </div>
     </div>
        </form>
    </div>
  </div>
  <div id="bg-modal2"  class="hidden2">
    <div class="entries">
      <form method="POST">
          {% csrf_token %}
          {{from.as_p}}
     <h2>Add members</h2>
     <div class="wrapper">
        <div class="form">
      <form method="POST" enctype="multipart/form-data">
         {%csrf_token%}
         {{form.as_p}}
         {{Name}}
         <button class="submit2">Submit</button>
     </form>
    </div>
    </div>
     </div>
      </form>
    </div>
  </div>
<script>
  function toggleAddBtn() {
    var div = document.getElementById("bg-modal");
     div.style.position='absolute'
     div.style.top = 0
     div.style.margin = '4% 32%'
     div.classList.toggle('hidden')
}
function toggleAddBtn2() {
    var div = document.getElementById("bg-modal2");
     div.style.position='absolute'
     div.style.top = 0
     div.style.margin = '4% 32%'
     div.classList.toggle('hidden2')
}
</script>
</div>
</body>
</html>

addgroup/templates/display_group.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
{% block title %}<title>Group List</title>{% endblock %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
</head>
<body>
<style type="text/css">
body{
 background-color:#b4bfcc;
  font-family: Arial, Helvetica, sans-serif;
}
h1{
  font-family: 'Nunito', sans-serif;
  font-weight: 900;
}
#group{
  text-decoration: none;
}
.sidebar-nav{
  height: 100%;
  width: 180px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color:#192E5B;
  overflow: hidden;
  padding-top: 20px;
 }
.sidebar-nav a{
    padding:13px 13px 13px 30px;
    text-decoration: none;
    font-size: 18px;
    color: #F1F1F1;
    display: block;
    font-family: 'Nunito', sans-serif;
    font-weight: bold;
    }
.sidebar-nav a:hover{
  color: black;
}
.content{
 align-items: center;
}

#groups{
  padding-left: 30%;
  color: black;
}
.topnav {
overflow: hidden;
padding-left: 40%;
}
.dropdown {
 float: left;
 overflow: hidden;
 margin-left: 34%;
 width: 200px;
}
.dropdown .dropbtn {
 font-size: 16px;
 border: none;
 outline: none;
 color: black;
 padding: 14px 16px;
 background-color: inherit;
 font-family: inherit;
 margin: 0;
 }
.navbar a:hover, .dropdown:hover .dropbtn {
 cursor: pointer;
}
.dropdown-content {
 display: none;
 position: absolute;
 background-color: #F9F9F9;
 min-width: 170px;
 box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
 margin-bottom: -20%;
 }
.dropdown-content a {
 float: none;
 color: black;
 padding: 12px 16px;
 text-decoration: none;
 display: block;
 text-align: left;
}
.dropdown:hover .dropdown-content {
 display: block;
}
.dropdown-menu ul{
 list-style: none;
 display: flex;
 margin: 0%;
}
#info{
font-weight: bold;
font-family: 'Nunito', sans-serif;
background: none;
border: none;
font-size: 15px;
}
.group{
margin-left: 190px;
}
.groups{
margin-left: 200px;
}
.dropbtn{
 position: relative;
  bottom: -45px;
  padding-right: 30px;
}
#grp{
 color: white;
}
#grp:hover{
 color: black;
}
#name{
 padding-bottom: -15%;
 font-family: 'Nunito', sans-serif;
}
#image{
    width: 35px;
  }
  #img{
    width: 23px;
  }
.addbutton {
  background-color: #192E5B;
  border: none;
  color: #FFFFFF;
  padding: 5px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 20px;
  margin-left: 1100px;
  position: relative;
  bottom: -350px;
  border-radius: 10px;
  cursor: pointer;
  border-radius: 50%;
}
#table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 70%;
            margin-left: 20%;
            font-family: 'Nunito', sans-serif;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
            font-family: 'Nunito', sans-serif;
            margin-left: 20%;
        }
        #table tr:nth-child(even){
            background-color: #f2f2f2be;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
            font-family: 'Nunito', sans-serif;
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            padding: -5px;
            color:black;
            font-family: 'Nunito', sans-serif;
        }
        td a{
          margin-left: 10%;
          color: black;
        }
        #one{
          padding-left: 7%;
        }
        #two{
          padding-left: 2%;
        }


@media screen and (max-width: 960px) {
  .sidebar-nav >a {
     font-size: 13px;
    margin-top: -15px;
    height: 30px;
  }
  }
@media screen and (max-width: 960px) {
  .sidebar-nav{
    height: 90%;
    width: 12%;
  }
}
@media screen and (max-width: 768px) {
  .dropdown{
  margin-left:4%;
  margin-bottom:-2%;
   }
}
@media screen and (max-width: 768px) {
table, td, th{
margin-right: 2%;
 }
}
@media screen and (max-width: 768px) {
  h1{
    font-size: 20px;
    margin-left: 30%;
  }
}
@media screen and (max-width: 768px) {
th, td {
padding: 15px;
margin-top: -9%;
}
}
 @media screen and (min-width: 400px) {
tr, th{
  padding:14px 14px 14px 18px;
 }
}
@media screen and (min-width: 400px) {
.addbutton{
 right:90%;
 }
}


</style>
</head>
<body>
<button class="addbutton"><a href="{% url 'addgroup:add_group' %}">+</a></button>
<div class="content" >
      <div class="sidebar-nav">
        <img src="{% static 'imges/Farm to Plate.png' %}" alt="" style="width: 90px; height: 90px; margin-left: 28px; margin-bottom: 20px; border-radius: 5%;">
        <a href="{% url 'addgroup:display_group' %}">Home</a>
        <a href="{% url 'addgroup:add_group' %}" id="grp" >Add group</a>
        <a href="{% url 'group_details:list' %}">Deliveries</a>
        <a href="{% url 'payments:payments' %}">Payments</a>
        <a href="{%url 'setting_page'%}">Settings</a>
        <a href="{% url 'login'%}">LogOut</a>
      </div>
 </div>
       <table id="table">
         <center><h1>Group List</h1></center>
         <hr>
        <tr>
         
            <th id="name" >Group name</th>
            <th> Group members</th>
            <th>Group leader contact</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <tr>
          {% for group in groups %}

            <td><a href="{% url 'group_details:group_details' id=group.id %}" id="group" >{{group.group_name}}</a>{{group.no_of_group_member}}</td>
            <td id="one"  >{{group.no_of_members}}</td>
            <td id="two" >{{group.phone_number}}</td>
            <td><a href="{% url 'group_details:group_details' id=group.id %}"><img src="https://icons-for-free.com/iconfiles/png/512/svg+create+edit+edit+file+office+pencil+writing+creativ+icon-1320185158722776676.png" alt="" id="image"></a></td>
            <td><a href="{% url 'group_details:group_details' id=group.id %}"><img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/delete-2471204-2066711.png" alt="" id="img"></a></td>
        </tr> 
        {%endfor%}
    </table>
</body>
</html>

addgroup/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        <h1> Edit details </h1>
        {{form.as_p}}
        <input type="submit" value="Submit" id="button">
    </form>
    <table id="table">
        {% for group_details in product %}
        <tr>
          <td>{{group_details.date_of_delivery}}</td>
          <td>{{group_details.beans_variety}}</td>
          <td>{{group_details.group_name}}</td>
          <td>{{group_details.kgs_of_beans}}</td>
          <td>{{group_details.Price_per_kg}}</td>
          <td>{{group_details.total_amount}}</td>
      </tr>
      {% endfor %}
    </table>
    <style>
        #table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 20%;
            font-family: 'Nunito', sans-serif;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
        }
        #table tr:nth-child(even){
            background-color: #f2f2f2be;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            color:black;
            font-family: 'Nunito', sans-serif;
        }
    </style>
</body>
</html>