Agricoop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('registration.urls')),
    path('addgroup/',include('addgroup.urls')),
    path("group_details/",include("group_details.urls")),
    path("payments/",include("payments.urls")),
    path('settings/', include("settings.urls")),
    path('mympesa', include('mympesa.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns +=staticfiles_urlpatterns()

Api/urls.py
from django.urls.conf import include, path
from rest_framework import routers
from .views import LoginViewSet
from .views import SignUpViewSet
from .views import PaymentViewSet
from .views import BaseModelViewset
from .views import MpesaCallsViewset
from .views import MpesaCallBacksViewset
from .views import MpesaPaymentViewset
router=routers.DefaultRouter()
router.register("login/",LoginViewSet)
router.register("register/",SignUpViewSet)
router.register("dashboard/",PaymentViewSet)
router.register("basemodel/",BaseModelViewset)
router.register("mpesacalls/",MpesaCallsViewset)
router.register("mpesacallbacks/",MpesaCallBacksViewset)
router.register("mpesapayment/",MpesaPaymentViewset)
urlpatterns = [
   path("",include(router.urls))
]

addgroup/urls.py
from django.urls import path
from .views import add_group,display_group


app_name = 'addgroup'
urlpatterns = [
    path("add_group/",add_group,name="add_group"),
    path("display/", display_group, name="display_group"),
]
    

group_details/urls.py
from django.urls import path

from .views import group_details,display_beans,edit,delete

app_name = 'group_details'
urlpatterns = [

        path("group_details/<int:id>/",group_details,name="group_details"),
        path("group_details/",display_beans,name="list"),
        path("edit/<int:id>/",edit,name="edit"),
        path("delete/<int:id>/",delete,name="delete")
]

payments/urls.py
from django.urls import path
from .views import payments,payment_list,edit,delete,lipa
from django.conf import urls
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


app_name = 'payments'
urlpatterns = [
    path("payments/",payments,name="payments"),
    path("list/",payment_list,name="payment_list"),
    path("edit/<int:id>/",edit,name="edit"),
    path("delete/<int:id>/",delete,name="delete"),
    path("lipa",lipa,name="lipa"),
    

]

payments/models.py
from django.db import models
from django.db.models import fields
from django.db.models.deletion import CASCADE
from django.db.models.fields import BigIntegerField

from addgroup.models import Group_list
from group_details.models import Delivaries


status_choice=(
        ('Paid','Paid'),
        ('Unpaid','Unpaid'),
        ('Rejected','Rejected')
    )
class Payments(models.Model):
    total_quantity_purchased=BigIntegerField
    date_of_delivery=models.DateField(auto_now_add=True)
    add_group=models.ForeignKey(Group_list,on_delete=CASCADE ,null=True)
    amount=models.ForeignKey(Delivaries,on_delete=CASCADE,null=True)
    payment_status=models.CharField(max_length=200,null=True,default="Unpaid")


class Lipa(models.Model):
    phone_number=models.CharField(max_length=300,null=True)
    pay_bill=models.IntegerField(null=True)
    amount_paid=models.BigIntegerField(null=True)
    

payments/forms.py
from django import forms
from django.forms import fields
from .models import Lipa, Payments

class PaymentsDetailsRegistrationForm():

    class Meta:
        model:Payments
        fields='__all__'


class LipaRegistrationForm():   
    class Meta:
        model:Lipa
        fields='__all__'

payments/views.py
from django.shortcuts import render
from django import forms
from django.shortcuts import  render, redirect
from group_details.forms import GroupRegistrationForm
from group_details.models import Delivaries
from django.http.response import HttpResponse
from payments.models import Payments
from addgroup.models import Group_list
from .forms import LipaRegistrationForm, PaymentsDetailsRegistrationForm
from django.urls import reverse
from django.http.response import HttpResponseRedirect


def payments(request):
    return render(request,"payment.html",{"forms":forms})


def payment_list(request):
    payments=Payments.objects.all()
    groups=Group_list.objects.all()
    batch=Delivaries.objects.all()
    return render(request,"payment_list.html",{"payments":payments,"groups":groups,"batch":batch})

def edit(request,id):
    groups=Group_list.objects.get(id=id)
    if request.method=="POST":
        form=GroupRegistrationForm(request.POST,instance=groups)
        if form.is_valid():
            form.save() 
            return redirect("payments:payments_list")
    else:
        form=GroupRegistrationForm(instance=groups)
        return render(request,"edit.html",{"form":form})

def delete(request,id):
    payment=Payments.objects.get(id=id)
    if request.method=='POST':
        payment.delete()
        return HttpResponseRedirect(reverse("payments:payments_list"))
    context={"payment":payment}
    return render(request,'delete.html')

def total_amount(self):
    total_amount=self.kgs_of_beans*self.price_per_kg
    return total_amount
    
def lipa(request):
    if request.method=="POST":
        form=LipaRegistrationForm (request.POST)
        if form.is_valid():
            form.save() 
    else:
        form=LipaRegistrationForm()
    return render(request,"payment_list.html",{"form":form})

payments/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Are you sure you want to delete?</p>
    <a href="{% url 'group_details:list' %}"><button>Cancel</button></a>
    <form method="POST" action="">
    {% csrf_token %}
    <input type="submit" name="confirm">
</form>
</body>
</html>
11:39
edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        <h1> Edit details </h1>
        {{form.as_p}}
        <input type="submit" value="Submit" id="button">
    </form>
    <table id="table">
        {% for payment in groups %}
<tr>
    <td>{{payment.group_name}}</td>
    <td>{{payment.phone_number}}</td>

</tr>
{%endfor%}
    </table>
    <style>
        #table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 20%;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
        }
        #table tr:nth-child(even){
            background-color: #f2f2f2be;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            color:black;
        }
    </style>
</body>
</html>

payments/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        <h1> Edit details </h1>
        {{form.as_p}}
        <input type="submit" value="Submit" id="button">
    </form>
    <table id="table">
        {% for payment in groups %}
        <tr>
            <td>{{payment.group_name}}</td>
            <td>{{payment.phone_number}}</td>
        
        </tr>
        {%endfor%}
    </table>
    <style>
        #table {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 20%;
         } ;
        #table td, #table th {
            border: 1px solid rgb(15, 15, 15);
            padding: 8px;
            
        }
        #table tr:nth-child(even){
            background-color: #f2f2f2be;
        }
        #table tr:hover {
            background-color: rgba(221, 221, 221, 0.192);
        }
        #table th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            color:black;
          
        }
    </style>
</body>
</html>

payments/templates/payment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Payments</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
  <style type="text/css">
  body{
    background-color:#b4bfcc;
    margin-top: 0;
  }
  form{
     padding: 15%;
     margin-top: 15%;
  }
  .sidebar-nav{
    height: 100%;
    width: 180px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color:#192E5B;
    overflow: hidden;
    padding-top: 20px;
  }
  .sidebar-nav a{
    padding:13px 13px 13px 30px;
    text-decoration: none;
    font-size: 18px;
    color: #F1F1F1;
    display: block;
    font-family: 'Nunito', sans-serif;
    font-weight: bold;
    }
  .sidebar-nav a:hover{
    color: black;
        }
  h1{
    text-align: center;
    text-decoration-color: black;
    margin-bottom: 7%;
    padding-left: 3%;
    font-family: 'Nunito', sans-serif;
  }
  form{
    margin-top:-250px;
    margin-left: 30%;
  }
  </style>
</head>
<body>
<div class="content" >
  <h1>Payments</h1>
        <div class="sidebar-nav">
          <img src="{% static 'imges/Farm to Plate.png' %}" alt="" style="width: 90px; height: 90px; margin-left: 28px; margin-bottom: 20px; border-radius: 5%;">
          <a href="{% url 'addgroup:display_group' %}">Home</a>
           <a href="{% url 'addgroup:add_group' %}">Add Group</a>
          <a href="{%url 'group_details:list' %}">Deliveries</a>
          <a href="{% url 'payments:payments' %}">Payments</a>
          <a href="{%url 'setting_page'%}">Settings</a>
          <a href="{% url 'login'%}">LogOut</a>
        </div>
   </div>
  <form action="/action_page.php">
    <p>Please select your payment method:</p>
    <input type="radio" id="html" name="bulk_payment" value="HTML" onclick="functionCalled()">
    <label for="html">Bulk Payment</label><br>
    <input type="radio" id="css" name="bulk_payment" value="CSS" onclick="functionCalled()" >
    <label for="css">Single Payment</label><br>
  </form>
  </body>
  </html>
  <script>
     function functionCalled() {
          window.open("{%url 'payments:payment_list'%}"); //if you want to open in new window
          window.location = "{%url 'payments:payment_list'%}"; //if you want to redirect
     }
  </script>
</body>
</html>

payments/templates/payment_list.html
<!DOCTYPE html>
<html lang="en">

<head>

  <head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76"
      href="https://appsrv1-147a1.kxcdn.com/material-dashboard-pro/img/apple-icon.png">
    <link rel="icon" type="image/png" href="https://appsrv1-147a1.kxcdn.com/material-dashboard-pro/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' /> `d
    <link href="https://appsrv1-147a1.kxcdn.com/material-dashboard-pro/css/material-dashboard.min.css?v=2.1.2"
      rel="stylesheet" />
    <link href="https://appsrv1-147a1.kxcdn.com/material-dashboard-pro/demo/demo.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
  </head>
  {% block title %}<title>Payments</title>{% endblock %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <style type="text/css">
    body {
      margin-top: 0;
      background-color: #b4bfcc;
    }

    #image {
      width: 33px;
    }

    #img {
      width: 30px;
    }

    form {
      padding: 15%;
      margin-top: -15%;
    }

    .sidebar-nav {
      height: 100%;
      width: 180px;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #192E5B;
      overflow: hidden;
      padding-top: 20px;
      font-family: 'Nunito', sans-serif;
    }

    .sidebar-nav a {
      padding: 10px 10px 10px 30px;
      text-decoration: none;
      font-size: 18px;
      color: #F1F1F1;
      display: block;
      font-weight: bold;
    }

    .sidebar-nav a:hover {
      color: black;
    }

    h1 {
      color: black;
      text-align: center;
      font-size: 30px;
      text-decoration-color: black;
      margin-top: 0%;
      padding-left: 3%;
      font-family: 'Nunito', sans-serif;
    }

    #table {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 80%;
      margin-left: 20%;
    }

    ;

    #table td,
    #table th {
      border: 1px solid rgb(15, 15, 15);
      padding: 8px;
    }

    td {
      color: black;
      font-family: 'Nunito', sans-serif;
    }

    #table tr:nth-child(even) {
      background-color: #f2f2f2be;
    }

    #table tr:hover {
      background-color: rgba(221, 221, 221, 0.192);
    }

    #table th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      color: black;
      font-family: 'Nunito', sans-serif;
    }

    #submit2 {
      text-decoration-style: none;
      height: 50px;
      width: 20%;
      border-radius: 6px;
      align-items: center;
      font-size: 1.4rem;
      margin-left: 75%;
      margin-top: 23%;
      background-color: #192E5B;
      color: white;
    }

    .hidden2 {
       display: none;
       color: black;
    }

    .entries {
      background-color: whitesmoke;
      border-radius: 20px;
      box-shadow: black 1px;
      margin-left: 100%;
      margin-top:35px;
      width: 400px;
      font-family: 'Nunito', sans-serif;
    }

    .butt {
      color: white;
      font-size: 18px;
    }
    h6{
      text-align: center;
      position: relative;
      bottom: 50px;
    }

    .butt:hover {
      color: black;
    }
    .submit{
      text-decoration-style: none;
      height: 30px;
      width: 20%;
      border-radius: 6px;
      align-items: center;
      font-size: 12px;
      background-color: #192E5B;
      color: white;
      margin-top: 20px;
      margin-right:19%;
      position: relative;
      bottom: -40px;
      right: 70px;
      
    }
     .status{
      right: 90px;
      position: relative;
    }
    #amount{
    
      bottom: -5px;
      color: black;
    } 
    #pay{
      padding-bottom: 3%;
    }
    #inputone{
      border-radius: 10px;
      border: none;
    }
    #inputtwo{
      border-radius: 10px;
      border: none;
    }
    #inputthree{
      border-radius: 10px;
      border: none;
    }
    #label{
      color: black;
    }
  </style>
  <div class="content">
    <div class="sidebar-nav">
      <img src="{% static 'imges/Farm to Plate.png' %}" alt=""
        style="width: 90px; height: 90px; margin-left: 28px; margin-bottom: 20px; border-radius: 5%;">
      <a href="{% url 'addgroup:display_group' %}">Home</a>
      <a href="{% url 'addgroup:add_group' %}">Add Group</a>
      <a href="{%url 'group_details:list' %}">Deliveries</a>
      <a href="">Payment</a>
      <a href="">Setting</a>
      <a href="">LogOut</a>
    </div>
  </div>
  <table id="table">
    <h1>Payments</h1>

    <tr>
      <hr>
      <th>Group name</th>
      <th>Phone number</th>
      <th>Total amount</th>
      <th>Paid amount</th>
      <th>Status</th>

    </tr>

    <tr>
      {% for payment in groups %}
    <tr>
      <td>{{payment.group_name}}</td>
      <td>{{payment.phone_number}}</td>

      {% for pay in batch %}
      <td>{{pay.total_amount}}</td>
      {% endfor%}
      <td>{{payment.amount_paid}}</td>
      <div class="status">
      <td >{{payment.payment_status}}</td>
    </div>
    </tr>
    {%endfor%}

  </table>
 

  <div id="bg-modal2" class="hidden2">
    <!-- <h6>make payments</h6> -->
    <div class="entries">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ fom.as_p}}
       <label for="" id="label">Phone Number</label>
       <input type="text" style="width: 80px;" id="inputone"><br>
       <label for="" id="label">Paybill</label>
       <input style="width: 80px;" type="text" id="inputtwo"><br>
       <label id="amount" for="">Enter amount</label>
       <input style="width: 80px;" type="text" id="inputthree">
       <button class="submit">submit</button>
      </form>
    </div>
    </form>
  </div>
  <button id="submit2" onclick="toggleAddBtn()">Make Payments</a></button>
  </div>


  <script>
    function toggleAddBtn() {
      var div = document.getElementById("bg-modal2");
      div.style.position = 'absolute'
      div.style.top = 5
      div.style.left = 20
      div.style.margin = '4% 32%'
      div.classList.toggle('hidden2')
    }
  </script>
</body>

</html>